config/routes.rb
Rails.application.routes.draw do

  root 'homepages#index'
  get 'homepages/index'

  resources :homepages
  resources :projects
  resources :customers do
    resources :coworkers
  end
  resources :mytasks
  resources :qas
  resources :teams
  resources :gdrives

  get 'customers/:id/projects', to: 'customers#projects#show', :as => :customer_projects
  get 'projects/:id/qas', to: 'projects#qas#show', :as => :project_qas


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coworker.rb
class Coworker < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :projects, dependent: :nullify
  has_many :coworkers, dependent: :nullify

end

app/models/mytask.rb
class Mytask < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :customer

end

app/models/qa.rb
class Qa < ApplicationRecord
  belongs_to :project
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/coworkers_controller.rb
class CoworkersController < ApplicationController

  def new
    @customer = Customer.find(params[:customer_id])
    @coworker = Coworker.new
  end

  def edit
    @customer = Customer.find(params[:customer_id])
    @coworker = Coworker.find(params[:id])
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @coworker = @customer.coworkers.create(coworker_params)
    redirect_to customer_path(@customer)
  end

  def update
    @customer = Customer.find(params[:customer_id])
    @coworker = Coworker.find(params[:id])
    if @coworker.update(coworker_params)
      redirect_to customer_path(@customer)
    end
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @coworker = @customer.coworkers.find(params[:id])
    @coworker.destroy
    redirect_to customer_path(@customer)
  end

  private
  def coworker_params
    params.require(:coworker).permit(:coworker_name,
                                     :coworker_position,
                                     :coworker_phone,
                                     :coworker_skype,
                                     :coworker_email)
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def projects
    @customer = Customer.find(params[:id])
    @customer.projects
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.create(customer_params).save
    redirect_to customers_path
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end


  private
  def customer_params
    params.require(:customer).permit(:name)
  end

end

app/controllers/gdrives_controller.rb
class GdrivesController < ApplicationController



end

app/controllers/mytasks_controller.rb
class MytasksController < ApplicationController

  def index
    @mytask = Mytask.all
  end

  def show
    @mytask = Mytask.find(params[:id])
  end

  def new
    @mytask = Mytask.new
  end

  def edit
    @mytask = Mytask.find(params[:id])
  end

  def create
    @mytask = Mytask.create(mytasks_params).save
    redirect_to mytasks_path
  end

  def update
    @mytask = Mytask.find(params[:id])
    if @mytask.update(mytasks_params)
      redirect_to mytasks_path
    end
  end

  def destroy
    @mytask = Mytask.find(params[:id]).destroy
    redirect_to mytasks_path
  end

  private

  def mytasks_params
    params.require(:mytask).permit(:taskname, :taskcontent, :taskstatus, :createtask, :endtask)
  end






end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.create(project_params).save
    redirect_to projects_path
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end


  private
  def project_params
    params.require(:project).permit(:name, :description, :status, :startdate, :enddate, :receive, :customer_id )

  end

end

app/controllers/qas_controller.rb
class QasController < ApplicationController

  def index
    @qas = Qa.all
  end




end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.create(team_params)
    redirect_to teams_path
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path
  end


  private

  def team_params
    params.require(:team).permit(:name,
                                 :position,
                                 :phone,
                                 :skype,
                                 :email,
                                 :birthday,
                                 :hired)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coworkers_helper.rb
module CoworkersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gdrives_helper.rb
module GdrivesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/mytasks_helper.rb
module MytasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/coworkers/_coworker.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th>Phone</th>
    <th>Skype</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <% @customer.coworkers.each do |coworker| %>
      <tr>
        <td><%= coworker.coworker_name %></td>
        <td><%= coworker.coworker_position %></td>
        <td><%= coworker.coworker_phone %></td>
        <td><%= coworker.coworker_skype %></td>
        <td><%= coworker.coworker_email %></td>
        <td class="icon-td"><%= link_to '', edit_customer_coworker_path(coworker), class: "glyphicon glyphicon-edit icon-edit" %></td>
        <td class="icon-td"><%= link_to '', [coworker.customer, coworker],
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' },
                                        class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
  <% end %>
</table>

app/views/coworkers/_form.html.erb
<h2>Add a coworker:</h2>
<%= form_for([@customer, @coworker]) do |f| %>
    <p>
      <%= f.label :coworker_name %><br>
      <%= f.text_field :coworker_name %>
    </p>
    <p>
      <%= f.label :coworker_position %><br>
      <%= f.text_area :coworker_position %>
    </p>
    <p>
      <%= f.label :coworker_phone %><br>
      <%= f.text_area :coworker_phone %>
    </p>
    <p>
      <%= f.label :coworker_skype %><br>
      <%= f.text_area :coworker_skype %>
    </p>
    <p>
      <%= f.label :coworker_email %><br>
      <%= f.text_area :coworker_email %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>


    <div class='actions'>
      <%= f.submit :class => 'btn btn-default' %>
    </div>


    <p>
      <%= link_to 'Back', customers_path, class: "btn btn-default" %>
    </p>

<% end %>

app/views/customers/index.html.erb
<h3>Customers</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td class="icon-td"><%= link_to '', customer_projects_path(customer.id), class: "glyphicon glyphicon-briefcase" %></td>
        <td class="icon-td"><%= link_to '', customer_path(customer), class: "glyphicon glyphicon-folder-open icon-open" %></td>
        <td class="icon-td"><%= link_to '', edit_customer_path(customer), class: "glyphicon glyphicon-edit icon-edit" %></td>
        <td class="icon-td"><%= link_to '', customer,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
  <% end %>
</table>


<p>
  <%= link_to new_customer_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-plus-sign"></i> Add Customer
  <% end %>
</p>

app/views/customers/projects.html.erb
<h3>Customer Projects</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Project</th>
    <th>Description</th>
    <th>Status</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Receive Date</th>
    <th>Customer</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <% @customer.projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.status %></td>
        <td><%= project.startdate %></td>
        <td><%= project.enddate %></td>
        <td><%= project.receive %></td>
        <td><%= project.customer.name %></td>
        <td><%= link_to '', project_path(project), class: "glyphicon glyphicon-folder-open icon-open" %></td>
        <td><%= link_to '', edit_project_path(project), class: "glyphicon glyphicon-edit icon-edit" %></td>
        <td><%= link_to '', project,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
  <% end %>

</table>

<p>
  <%= link_to new_project_path, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-plus-sign"></i> Add Project
  <% end %>
</p>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <%= link_to '', edit_customer_path, class: "glyphicon glyphicon-edit icon-edit" %>
</p>


<h3>Coworkers</h3>
<%= render 'coworkers/coworker' %>

<%= link_to 'New coworker',  new_customer_coworker_path(@customer.id), class: "btn btn-default" %>

<p>
  <%= link_to 'Back', customers_path, class: "btn btn-default" %>
</p>

app/views/mytasks/_form.html.erb
<%= form_for @mytask do |f| %>

    <div class='input_form'>
      <%= f.label :taskname %><br>
      <%= f.text_field :taskname, class: 'form-control' %>
    </div>

    <div class='input_form'>
      <%= f.label :taskcontent %><br>
      <%= f.text_field :taskcontent, class: 'form-control' %>
    </div>

    <div class='select_form'>
      <%= f.label :taskstatus %><br>
      <%= select(:mytask, :taskstatus, [ ['Waiting...', 'Waiting...'],
                                      ['Done', 'Done'],
                                      ['Active', 'Active'],
                                      ['In Testing', 'In Testing'] ],
                                      :include_blank => true,
                                      :default => nil) %>
    </div>

    <div class='datepicker_form'>
      <%= f.label :createtask %>
      <div class="input-group date">
        <%= f.text_field :createtask, class: 'form-control' %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>

    <div class='datepicker_form'>
      <%= f.label :endtask %>
      <div class="input-group date">
        <%= f.text_field :endtask, class: 'form-control' %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>


    <div class='actions'>
      <%= f.submit :class => 'btn btn-default' %>
    </div>

    <p>
      <%= link_to 'Back', mytasks_path, class: 'btn btn-default' %>
    </p>



    <%= javascript_include_tag 'datepicker' %>

<% end %>

app/views/mytasks/index.html.erb
<h3>My Tasks</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Cteated</th>
    <th>Finished</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <% @mytask.each do |mytask| %>
      <tr>
        <td><%= mytask.taskname %></td>
        <td><%= mytask.taskcontent %></td>
        <td><%= mytask.taskstatus %></td>
        <td><%= mytask.createtask %></td>
        <td><%= mytask.endtask %></td>
        <td><%= link_to '', mytask_path(mytask), class: "glyphicon glyphicon-folder-open icon-open" %></td>
        <td><%= link_to '', edit_mytask_path(mytask), class: "glyphicon glyphicon-edit icon-edit" %></td>
        <td><%= link_to '', mytask,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
  <% end %>

</table>

<p>
  <%= link_to new_mytask_path, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-plus-sign"></i> Add Task
  <% end %>
</p>

app/views/mytasks/show.html.erb
<h3>My Tasks</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Cteated</th>
    <th>Finished</th>
    <th colspan="3"></th>
  </tr>
  </thead>

      <tr>
        <td><%= @mytask.taskname %></td>
        <td><%= @mytask.taskcontent %></td>
        <td><%= @mytask.taskstatus %></td>
        <td><%= @mytask.createtask %></td>
        <td><%= @mytask.endtask %></td>
        <td><%= link_to '', edit_mytask_path(@mytask), class: "glyphicon glyphicon-edit icon-edit" %></td>
        <td><%= link_to '', @mytask,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>

</table>

<p>
  <%= link_to 'Back', mytasks_path, class: "btn btn-default" %>
</p>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

    <div class='input_form'>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class='input_form'>
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class='select_form'>
      <%= f.label :status %><br>
      <%= select(:project, :status, [ ['Waiting...', 'Waiting...'],
                                      ['Done', 'Done'],
                                      ['Active', 'Active'],
                                      ['In Testing', 'In Testing'] ],
                                      :include_blank => true,
                                      :default => nil) %>
    </div>

    <div class='datepicker_form'>
      <%= f.label :startdate %>
      <div class="input-group date">
        <%= f.text_field :startdate, class: 'form-control' %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>

    <div class='datepicker_form'>
      <%= f.label :enddate %>
      <div class="input-group date">
        <%= f.text_field :enddate, class: 'form-control' %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>

    <div class='datepicker_form'>
      <%= f.label :receive %>
      <div class="input-group date">
        <%= f.text_field :receive, class: 'form-control'  %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>

    <div class='select_form'>
      <%= collection_select(:project, :customer_id, Customer.all, :id, :name, :include_blank => true, :default => nil) %>
    </div>

    <div class='actions'>
      <%= f.submit :class => 'btn btn-default' %>
    </div>

    <p>
      <%= link_to 'Back', projects_path, class: 'btn btn-default' %>
    </p>



    <%= javascript_include_tag 'datepicker' %>

<% end %>

app/views/projects/index.html.erb
<h3>Projects</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
      <th>Status</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Receive Date</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.status %></td>
      <td><%= project.startdate %></td>
      <td><%= project.enddate %></td>
      <td><%= project.receive %></td>
      <td><%= !project.customer.nil? ? project.customer.name : '' %></td>
      <td><%= link_to '', project_path(project), class: "glyphicon glyphicon-folder-open icon-open" %></td>
      <td><%= link_to '', edit_project_path(project), class: "glyphicon glyphicon-edit icon-edit" %></td>
      <td><%= link_to '', project,
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "glyphicon glyphicon-trash" %>
      </td>
    </tr>
  <% end %>

</table>

<p>
  <%= link_to new_project_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-plus-sign"></i> Add Project
  <% end %>
</p>

app/views/projects/show.html.erb
<h3>Project Details</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Project</th>
    <th>Description</th>
    <th>Status</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Receive Date</th>
    <th>Customer</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @project.name %></td>
      <td><%= @project.description %></td>
      <td><%= @project.status %></td>
      <td><%= @project.startdate %></td>
      <td><%= @project.enddate %></td>
      <td><%= @project.receive %></td>
      <td><%= !@project.customer.nil? ? @project.customer.name : '' %></td>
      <td><%= link_to '', edit_project_path, class: "glyphicon glyphicon-edit icon-edit" %></td>
      <td><%= link_to '', @project,
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "glyphicon glyphicon-trash" %>
      </td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to 'Back', projects_path, class: "btn btn-default" %>
</p>

app/views/qas/index.html.erb
<h3>QA</h3>
<h4>Here will be checklists, testcases, new features and requirements to each project</h4>