config/routes.rb
Rails.application.routes.draw do

  root 'homepages#index'
  get 'homepages/index'

  resources :homepages
  resources :projects
  resources :customers do
    resources :coworkers
  end
  resources :mytasks
  resources :qas
  resources :teams
  resources :gdrives

  get 'customers/:id/projects', to: 'customers#projects#show', :as => :customer_projects
  get 'projects/:id/qas', to: 'projects#qas#show', :as => :project_qas


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coworker.rb
class Coworker < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :projects, dependent: :nullify
  has_many :coworkers, dependent: :nullify

end

app/models/mytask.rb
class Mytask < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :customer

end

app/models/qa.rb
class Qa < ApplicationRecord
  belongs_to :project
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/gdrives_controller.rb
class GdrivesController < ApplicationController



end

app/controllers/mytasks_controller.rb
class MytasksController < ApplicationController

  def index
    @mytask = Mytask.all
  end

  def show
    @mytask = Mytask.find(params[:id])
  end

  def new
    @mytask = Mytask.new
  end

  def edit
    @mytask = Mytask.find(params[:id])
  end

  def create
    @mytask = Mytask.create(mytasks_params).save
    redirect_to mytasks_path
  end

  def update
    @mytask = Mytask.find(params[:id])
    if @mytask.update(mytasks_params)
      redirect_to mytasks_path
    end
  end

  def destroy
    @mytask = Mytask.find(params[:id]).destroy
    redirect_to mytasks_path
  end

  private

  def mytasks_params
    params.require(:mytask).permit(:taskname, :taskcontent, :taskstatus, :createtask, :endtask)
  end






end

app/controllers/qas_controller.rb
class QasController < ApplicationController

  def index
    @qas = Qa.all
  end




end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.create(team_params)
    redirect_to teams_path
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path
  end


  private

  def team_params
    params.require(:team).permit(:name,
                                 :position,
                                 :phone,
                                 :skype,
                                 :email,
                                 :birthday,
                                 :hired)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coworkers_helper.rb
module CoworkersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gdrives_helper.rb
module GdrivesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/mytasks_helper.rb
module MytasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team Salt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header"><%= link_to image_tag('ts4.png'), root_path %>
        <%= link_to mytasks_path, class: "nav-link" do %>
          <i class="pull-right glyphicon  glyphicon-bell"></i>
        <% end %>
    </div>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class=" list-group">

            <li class="list-group-item">
              <%= link_to customers_path, class: "nav-link" do %>
                  <i class="pull-right glyphicon glyphicon-user"></i> Customers
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to projects_path, class: "nav-link" do %>
                  <i class="pull-right glyphicon glyphicon-briefcase"></i> Projects
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to qas_path, class: "nav-link" do %>
                  <i class="pull-right fa fa-bug"></i> QA
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to mytasks_path, class: "nav-link" do %>
                  <i class="pull-right glyphicon glyphicon-tasks"></i> My Tasks
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to teams_path, class: "nav-link" do %>
                  <i class="pull-right fa fa-users"></i> Team
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to mytasks_path, class: "nav-link" do %>
                  <i class="pull-right fa fa-clock-o"></i> Report
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to mytasks_path, class: "nav-link" do %>
                  <i class="pull-right fa fa-sticky-note"></i> Notes
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to gdrives_path, class: "nav-link" do %>
                  <i class="pull-right fa fa-google"></i> Google Drive
              <% end %>
            </li>

          </ul>
        </nav>

        <div class="col-sm-9 col-md-10 content"><%= yield %></div>

      </div>
    </div>
  </body>
</html>